[book]
authors = ["Insert5StarName", "hifinerd"]
language = "en"
multilingual = false
src = "src"
title = "MagmaWM - Documentation"
description = "Documentation for Magma Window Manager"
[output.html]
default-theme = "mocha"
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-highlight.css"]
git-repository-url = "https://github.com/MagmaWM/MagmaWM"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/MagmaWM/Docs/{path}"
